name: sample-rust-axum
services:
- name: axum
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: bojand/sample-rust-axum
  envs:
    - key: PUBLIC_URL
      scope: RUN_TIME
      value: ${_self.PUBLIC_URL}